# Render Blueprint to deploy n8n as a web service
# using CockroachDB instead of the default Render Postgres.
# Enhancements: custom webhook URL, persistent credentials,
# ready for external integrations.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Required encryption key for n8n credentials
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Database configuration — now using your CockroachDB cluster
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: autosocial-16264.j77.aws-ap-south-1.cockroachlabs.cloud
      - key: DB_POSTGRESDB_PORT
        value: "26257"
      - key: DB_POSTGRESDB_DATABASE
        value: defaultdb
      - key: DB_POSTGRESDB_USER
        value: goevergreen
      - key: DB_POSTGRESDB_PASSWORD
        value: 7BH6FBP9U3oCC0oR1dP38g
      - key: DB_POSTGRESDB_SSL_CA
        value: true
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "true"
      - key: DB_POSTGRESDB_SCHEMA
        value: public

      # Base URL for n8n webhooks and UI
      - key: N8N_HOST
        value: n8n.goevergreen.shop
      - key: WEBHOOK_URL
        value: https://n8n.goevergreen.shop/

      # Optional Enhancements
      # Limit execution concurrency (prevents Render free tier from choking)
      - key: EXECUTIONS_PROCESS
        value: main
      # Automatically prune old executions for disk health
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "336" # in hours (14 days)

      # Allow editor to import/export workflows easily
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n.goevergreen.shop/

      # Enable basic auth (recommended for public deployments)
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true

      # For easier troubleshooting
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: "*"

# Removed built-in Render Postgres; CockroachDB handles persistence